[ 2024-11-21 20:38:10,396 ] 18 root - INFO - Initiate the data ingestion
[ 2024-11-21 20:38:20,905 ] 65 root - INFO - Performed train test split on the dataframe
[ 2024-11-21 20:38:20,905 ] 67 root - INFO - Exited split_data_as_train_test method of Data_Ingestion class
[ 2024-11-21 20:38:20,906 ] 75 root - INFO - Exporting train and test file path.
[ 2024-11-21 20:38:20,958 ] 84 root - INFO - Exported train and test file path.
[ 2024-11-21 20:38:20,959 ] 20 root - INFO - Data Initiation Completed
[ 2024-11-21 20:38:20,966 ] 25 root - INFO - Initiate the data Validation
[ 2024-11-21 20:38:21,026 ] 32 root - INFO - Required number of columns:2
[ 2024-11-21 20:38:21,026 ] 33 root - INFO - Data frame has columns:31
[ 2024-11-21 20:38:21,027 ] 32 root - INFO - Required number of columns:2
[ 2024-11-21 20:38:21,027 ] 33 root - INFO - Data frame has columns:31
[ 2024-11-21 20:38:21,152 ] 27 root - INFO - data Validation Completed
[ 2024-11-21 20:38:21,153 ] 31 root - INFO - data Transformation started
[ 2024-11-21 20:38:21,154 ] 63 root - INFO - Entered initiate_data_transformation method of DataTransformation class
[ 2024-11-21 20:38:21,154 ] 65 root - INFO - Starting data transformation
[ 2024-11-21 20:38:21,175 ] 48 root - INFO - Entered get_data_trnasformer_object method of Trnasformation class
[ 2024-11-21 20:38:21,175 ] 53 root - INFO - Initialise KNNImputer with {'missing_values': nan, 'n_neighbors': 3, 'weights': 'uniform'}
[ 2024-11-21 20:38:21,189 ] 46 root - INFO - Entered the save_object method of MainUtils class
[ 2024-11-21 20:38:21,193 ] 50 root - INFO - Exited the save_object method of MainUtils class
[ 2024-11-21 20:38:21,194 ] 46 root - INFO - Entered the save_object method of MainUtils class
[ 2024-11-21 20:38:21,196 ] 50 root - INFO - Exited the save_object method of MainUtils class
[ 2024-11-21 20:38:21,198 ] 35 root - INFO - data Transformation completed
[ 2024-11-21 20:38:21,198 ] 38 root - INFO - Model Training stared
[ 2024-11-21 20:38:21,217 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\model_trainer.py] line number [114] error message [evaluate_models() got an unexpected keyword argument 'x_test']
[ 2024-11-21 20:38:21,220 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\model_trainer.py] line number [114] error message [evaluate_models() got an unexpected keyword argument 'x_test']
[ 2024-11-21 20:38:21,220 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\main.py] line number [40] error message [Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\model_trainer.py] line number [114] error message [evaluate_models() got an unexpected keyword argument 'x_test']]
[ 2024-11-21 20:38:21,220 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\model_trainer.py] line number [114] error message [evaluate_models() got an unexpected keyword argument 'x_test']
