[ 2024-11-22 14:32:56,284 ] 1038 httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2024-11-22 14:32:56,291 ] 107 dagshub - INFO - Accessing as akshatbindal
[ 2024-11-22 14:32:56,837 ] 1038 httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/repos/akshatbindal/Network-Security-DS-Project "HTTP/1.1 200 OK"
[ 2024-11-22 14:32:57,417 ] 1038 httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2024-11-22 14:32:57,420 ] 107 dagshub - INFO - Initialized MLflow to track repo "akshatbindal/Network-Security-DS-Project"
[ 2024-11-22 14:32:57,421 ] 107 dagshub - INFO - Repository akshatbindal/Network-Security-DS-Project initialized!
[ 2024-11-22 14:34:00,550 ] 34 root - INFO - Start data Ingestion
[ 2024-11-22 14:34:03,298 ] 65 root - INFO - Performed train test split on the dataframe
[ 2024-11-22 14:34:03,298 ] 67 root - INFO - Exited split_data_as_train_test method of Data_Ingestion class
[ 2024-11-22 14:34:03,299 ] 75 root - INFO - Exporting train and test file path.
[ 2024-11-22 14:34:03,371 ] 84 root - INFO - Exported train and test file path.
[ 2024-11-22 14:34:03,372 ] 37 root - INFO - Data ingestion completed and artifact: {data_ingestion_artifact}
[ 2024-11-22 14:34:03,399 ] 46 root - INFO - Initiate the data Validation
[ 2024-11-22 14:34:03,479 ] 32 root - INFO - Required number of columns:2
[ 2024-11-22 14:34:03,479 ] 33 root - INFO - Data frame has columns:31
[ 2024-11-22 14:34:03,479 ] 32 root - INFO - Required number of columns:2
[ 2024-11-22 14:34:03,479 ] 33 root - INFO - Data frame has columns:31
[ 2024-11-22 14:34:03,637 ] 57 root - INFO - Initiate the data Transformation
[ 2024-11-22 14:34:03,637 ] 63 root - INFO - Entered initiate_data_transformation method of DataTransformation class
[ 2024-11-22 14:34:03,637 ] 65 root - INFO - Starting data transformation
[ 2024-11-22 14:34:03,639 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\data_transformation.py] line number [66] error message ['DataIngestionArtifact' object has no attribute 'valid_train_file_path']
[ 2024-11-22 14:34:03,639 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\pipeline\training_pipeline.py] line number [58] error message [Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\data_transformation.py] line number [66] error message ['DataIngestionArtifact' object has no attribute 'valid_train_file_path']]
[ 2024-11-22 14:34:03,639 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\data_transformation.py] line number [66] error message ['DataIngestionArtifact' object has no attribute 'valid_train_file_path']
[ 2024-11-22 14:34:03,639 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\pipeline\training_pipeline.py] line number [85] error message [Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\pipeline\training_pipeline.py] line number [58] error message [Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\data_transformation.py] line number [66] error message ['DataIngestionArtifact' object has no attribute 'valid_train_file_path']]]
[ 2024-11-22 14:34:03,640 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\data_transformation.py] line number [66] error message ['DataIngestionArtifact' object has no attribute 'valid_train_file_path']
[ 2024-11-22 14:34:03,640 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\pipeline\training_pipeline.py] line number [58] error message [Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\data_transformation.py] line number [66] error message ['DataIngestionArtifact' object has no attribute 'valid_train_file_path']]
[ 2024-11-22 14:34:03,640 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\data_transformation.py] line number [66] error message ['DataIngestionArtifact' object has no attribute 'valid_train_file_path']
[ 2024-11-22 14:34:03,640 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\app.py] line number [54] error message [Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\pipeline\training_pipeline.py] line number [85] error message [Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\pipeline\training_pipeline.py] line number [58] error message [Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\data_transformation.py] line number [66] error message ['DataIngestionArtifact' object has no attribute 'valid_train_file_path']]]]
[ 2024-11-22 14:34:03,640 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\data_transformation.py] line number [66] error message ['DataIngestionArtifact' object has no attribute 'valid_train_file_path']
[ 2024-11-22 14:34:03,640 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\pipeline\training_pipeline.py] line number [58] error message [Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\data_transformation.py] line number [66] error message ['DataIngestionArtifact' object has no attribute 'valid_train_file_path']]
[ 2024-11-22 14:34:03,640 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\data_transformation.py] line number [66] error message ['DataIngestionArtifact' object has no attribute 'valid_train_file_path']
[ 2024-11-22 14:34:03,640 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\pipeline\training_pipeline.py] line number [85] error message [Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\pipeline\training_pipeline.py] line number [58] error message [Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\data_transformation.py] line number [66] error message ['DataIngestionArtifact' object has no attribute 'valid_train_file_path']]]
[ 2024-11-22 14:34:03,640 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\data_transformation.py] line number [66] error message ['DataIngestionArtifact' object has no attribute 'valid_train_file_path']
[ 2024-11-22 14:34:03,640 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\pipeline\training_pipeline.py] line number [58] error message [Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\data_transformation.py] line number [66] error message ['DataIngestionArtifact' object has no attribute 'valid_train_file_path']]
[ 2024-11-22 14:34:03,640 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\data_transformation.py] line number [66] error message ['DataIngestionArtifact' object has no attribute 'valid_train_file_path']
[ 2024-11-22 14:34:03,640 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\data_transformation.py] line number [66] error message ['DataIngestionArtifact' object has no attribute 'valid_train_file_path']
[ 2024-11-22 14:34:03,640 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\pipeline\training_pipeline.py] line number [58] error message [Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\data_transformation.py] line number [66] error message ['DataIngestionArtifact' object has no attribute 'valid_train_file_path']]
[ 2024-11-22 14:34:03,641 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\data_transformation.py] line number [66] error message ['DataIngestionArtifact' object has no attribute 'valid_train_file_path']
[ 2024-11-22 14:34:03,641 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\pipeline\training_pipeline.py] line number [85] error message [Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\pipeline\training_pipeline.py] line number [58] error message [Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\data_transformation.py] line number [66] error message ['DataIngestionArtifact' object has no attribute 'valid_train_file_path']]]
[ 2024-11-22 14:34:03,641 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\data_transformation.py] line number [66] error message ['DataIngestionArtifact' object has no attribute 'valid_train_file_path']
[ 2024-11-22 14:34:03,641 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\pipeline\training_pipeline.py] line number [58] error message [Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\data_transformation.py] line number [66] error message ['DataIngestionArtifact' object has no attribute 'valid_train_file_path']]
[ 2024-11-22 14:34:03,641 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\data_transformation.py] line number [66] error message ['DataIngestionArtifact' object has no attribute 'valid_train_file_path']
[ 2024-11-22 14:34:03,641 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\data_transformation.py] line number [66] error message ['DataIngestionArtifact' object has no attribute 'valid_train_file_path']
[ 2024-11-22 14:34:03,641 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\pipeline\training_pipeline.py] line number [58] error message [Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\data_transformation.py] line number [66] error message ['DataIngestionArtifact' object has no attribute 'valid_train_file_path']]
[ 2024-11-22 14:34:03,641 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\data_transformation.py] line number [66] error message ['DataIngestionArtifact' object has no attribute 'valid_train_file_path']
[ 2024-11-22 14:34:03,641 ] 13 root - INFO - Error occured in python script name [D:\MLOps\Network_Security_project\networksecurity\components\data_transformation.py] line number [66] error message ['DataIngestionArtifact' object has no attribute 'valid_train_file_path']
